name: hello world on merge

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Fixed typo (was "runs_on")

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Hello World
        run: echo "hello world, Noga's build successful"
